### ISSUE TITLE
能不能 添加多个桶同步功能，一般每个人都有N个桶，只能设置同步一个，有点小气。

### ISSUE THREAD

**Issue by drgsfgthfgklqwewerq** [TencentCloud/cosbrowser#107]
能不能 添加多个桶同步功能，一般每个人都有N个桶，只能设置同步一个，有点小气。

**Comment by carsonxu** [comment]
暂不考虑支持多个。

**Comment by drgsfgthfgklqwewerq** [comment]
人家百度云的桶 都支持多个哦。。
咱家差啥。。。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"carsonxu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 中午11:47
收件人:&nbsp;"tencentyun/cosbrowser"<cosbrowser@noreply.github.com&gt;;
抄送:&nbsp;"传奇好帮手"<cihua2018@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tencentyun/cosbrowser] 能不能 添加多个桶同步功能，一般每个人都有N个桶，只能设置同步一个，有点小气。 (#107)





 
暂不考虑支持多个。
