### ISSUE TITLE
一直加载中

### ISSUE THREAD

**Issue by leonard2z** [TencentCloud/cosbrowser#139]

**Comment by 2482103133** [comment]
![image](https://user-images.githubusercontent.com/37145130/103752718-07dfb900-5045-11eb-8afd-ac4b15bb17dd.png)

**Comment by Tencent-Alice** [comment]
您好，具体是什么操作的，可以简单描述下
技术问题，欢迎私信Q2562367495 注明来意

**Comment by carsonxu** [comment]
可以加Q或提工单，把日志文件发给我们具体排查下。@2482103133

**Comment by 2482103133** [comment]
QQ:2482103133

**Comment by 2482103133** [comment]
现在打开还是加载中,目前只能登录腾讯云网站手动更新文件,同步功能也不能使用.

**Comment by supermix** [comment]
我的cos browser 不显示文件。提示dns错误，但是我可以正常上网。
![image](https://user-images.githubusercontent.com/5841628/118104356-9efeb800-b40d-11eb-85f2-2e0179c7a2d9.png)
[cosbrowser.log](https://github.com/tencentyun/cosbrowser/files/6471489/cosbrowser.log)
解决后请联系我aidman@aliyun.com
