### ISSUE TITLE
iOS版cosbrowser无法开启文档预览

### ISSUE THREAD

**Issue by susc** [TencentCloud/cosbrowser#141]
打开pdf文件详情后，点击开启文档预览，但是转完圈还是没有打开，如下图所示：

![IMG_2077](https://user-images.githubusercontent.com/16367487/106238369-bdb0b880-623b-11eb-8684-963c69c10beb.png)

**Comment by konakonall** [comment]
@susc 请问下您是通过什么方式登录，微信/邮箱/密钥，另外身份是子账号还是主账号呢

**Comment by susc** [comment]
@konakonall 使用微信登陆（QQ），身份是主账号
