### ISSUE TITLE
希望mac版本dmg能打包成通用格式而不仅仅是X64

### ISSUE THREAD

**Issue by buildyuan** [TencentCloud/cosbrowser#144]
希望能够原生支持arm处理器

**Comment by Wonder233** [comment]
您好，当前 dmg 的安装是遇到什么问题了吗？

**Comment by buildyuan** [comment]
> 您好，当前 dmg 的安装是遇到什么问题了吗？

目前在Rosetta2 翻译下使用没有问题，只是一个建议。希望能够实现原生支持。

**Comment by carsonxu** [comment]
https://cloud.tencent.com/document/product/436/11366
已改为两个包：区分 macOS Intel 芯片版、macOS Apple 芯片版
