### ISSUE TITLE
希望支持默认上传文件的储存类型

### ISSUE THREAD

**Issue by yanmingrui96** [TencentCloud/cosbrowser#149]
比如可以快速修改一个文件夹内的所有文件的储存类型为低频或者其它类型

又或者可以直接在客户端设置默认上传类型

**Comment by Wonder233** [comment]
您好，目前可以在上传面板的下一步里进行一次性批量修改上传文件的存储类型。
![image](https://user-images.githubusercontent.com/8199240/114333560-2d67eb80-9b7b-11eb-875c-34791c7fbd5c.png)
![image](https://user-images.githubusercontent.com/8199240/114333576-35c02680-9b7b-11eb-9985-8f3e252ec585.png)

您说的这个功能我们需要评估一下~
