### ISSUE TITLE
客户端内存泄漏

### ISSUE THREAD

**Issue by xdusongwei** [TencentCloud/cosbrowser#151]
COSBrowser - 腾讯云 COS 客户端
v 2.6.2
Microsoft Windows [版本 10.0.19042.928]

下载归档发现内存泄漏
![task](https://user-images.githubusercontent.com/3774282/115517564-d8824e80-a2b9-11eb-8a32-ede1080bb191.PNG)
以及下载列表等待
![download](https://user-images.githubusercontent.com/3774282/115517816-20a17100-a2ba-11eb-9733-61baf035ac29.PNG)

下载期间我在设置中调整下载任务数从默认的5改成2

**Comment by songkeke** [comment]
什么都不敢，开一天，消耗内存40G
