### ISSUE TITLE
前进退后的逻辑问题

### ISSUE THREAD

**Issue by swoiow** [TencentCloud/cosbrowser#154]
1. mac 2.6.4
2. 使用鼠标退后，回退到登录界面，应该返回上级目录
3. 在2的基础上，前进没效果
4. 点登录有弹窗提示删除会话

**Comment by Wonder233** [comment]
您说的第 4 点出现的原因是在该会话已经被记住的条件下，将记住会话的选框给去掉了
![image](https://user-images.githubusercontent.com/8199240/120290291-c9e57900-c2f4-11eb-8d7a-d2efceb97107.png)
此时点击登录会弹窗提示：
<image src="https://user-images.githubusercontent.com/8199240/120290333-d4077780-c2f4-11eb-8132-4d9c2fb25812.png" width="400" />

另外，请问您说的鼠标退后是用了多按键鼠标，鼠标按键设置了浏览器前进后退行为，然后在 COSBrowser 上使用出现了您说的这种场景吗？

**Comment by swoiow** [comment]
> 您说的第 4 点出现的原因是在该会话已经被记住的条件下，将记住会话的选框给去掉了
> ![image](https://user-images.githubusercontent.com/8199240/120290291-c9e57900-c2f4-11eb-8d7a-d2efceb97107.png)
> 此时点击登录会弹窗提示：
> <img alt="" width="400" src="https://user-images.githubusercontent.com/8199240/120290333-d4077780-c2f4-11eb-8132-4d9c2fb25812.png">
> 
> 另外，请问您说的鼠标退后是用了多按键鼠标，鼠标按键设置了浏览器前进后退行为，然后在 COSBrowser 上使用出现了您说的这种场景吗？

是的，像这种 [JD](https://item.jd.com/40100120626.html )

**Comment by Wonder233** [comment]
这是正常表现。如果您之前勾选过记住会话，该会话会被放入历史会话中被记住。如果您下一次用同一个sid skey登录又把记住会话勾选去掉了，会认为您不想保存这次登录记录，因此会弹出提示询问您是否要删除这条登录记录。

**Comment by swoiow** [comment]
OK. 问题4的逻辑清楚了。问题2和3会考虑解决吗？

**Comment by Wonder233** [comment]
感谢反馈，后续版本会将鼠标快捷键屏蔽。
