### ISSUE TITLE
文件同步优化建议

### ISSUE THREAD

**Issue by minzojian** [TencentCloud/cosbrowser#158]
首先,cosbrowser是一个很方便的工具
我们在开发的过程中会经常直接拿cos做远程web项目的演示,因为可以随时修改随时交付给客户看.
所以会经常用到cosbrowser的文件同步的功能.
所以提出以下两个小建议来提升一下文件同步的体验.

1.建议加上过滤功能
象.git文件等一些没有必要上传的文件,就不要传了
和这个帖子一个意思
https://github.com/tencentyun/cosbrowser/issues/152

2.加上预校对功能
现在的比较文件是否相同还是一个一个去远端比较,这样效率太低了.建议采用一个日志文件,把最近一次同步的文件md5信息先存起来,在下次全量同步的时候,先在本地比较这个文件是否变化,如果有变化才上传,同时还要把这个日志文件也一并同步回cos远端目录下.
在做同步时,如果发现本地没有同步日志文件,但远程目录存在,就先把远端的下载下来,然后再重复上述本地比较的流程.

希望腾讯cosbrowser的小伙伴们能考虑一下以上两点建议
谢谢

**Comment by carsonxu** [comment]
关联 https://github.com/TencentCloud/cosbrowser/issues/152
