### ISSUE TITLE
建议Windows客户端文件同步功能增加过滤功能

### ISSUE THREAD

**Issue by iplaywind** [TencentCloud/cosbrowser#164]
COSBrower功能很好用，尤其问文件同步功能，可以将群晖的照片等重要文件备份到COS。
但是，群晖的照片会生成一些缩略图，COS以为缺少过滤功能，会将这些缩略图也备份到COS，造成不必要的资源浪费。
建议Windows客户端文件同步功能增加过滤功能，支持文件名和通配符的过滤，更加方便。

**Comment by iplaywind** [comment]
#152

**Comment by carsonxu** [comment]
已支持过滤后缀
