### ISSUE TITLE
太难了，想将本地的文件定时增量到COS，研究一天，发现提供的工具没有一个能完整的满足

### ISSUE THREAD

**Issue by xdkaka** [TencentCloud/cosbrowser#175]
1、cosbrowser增量同步，不支持过滤文件，不支持文件策略
2、costli不支持遍历子目录，有个递归-r参数，但是看了下代码，只是遍历了一层目录结构，子文件夹都会被忽略。。。。这么做意义是什么？对付代码么？
3、migrate提供三种过滤方式，无一能满足，要求提供的过滤文件必须是绝对路径。。。。

**Comment by carsonxu** [comment]
建议调用 SDK 实现。
