### ISSUE TITLE
ios客户端无法下载

### ISSUE THREAD

**Issue by notionchina** [TencentCloud/cosbrowser#180]
提示app不可用，无法下载

**Comment by 15809284891** [comment]
不好意思哈，COSBrowser目前存在一些内部问题，临时下架修复，正在重新上架。

**Comment by BaeKey** [comment]
大概需要多久，我就说我记得有ios的版本，我还下载过，结果怎么也搜索不到了

**Comment by BaeKey** [comment]
> 不好意思哈，COSBrowser目前存在一些内部问题，临时下架修复，正在重新上架。

大概需要多久，我就说我记得有ios的版本，我还下载过，结果怎么也搜索不到了

**Comment by kaze-kaze** [comment]
两个多月了....还没解决嘛，望能尽快上架（或者偷偷发个IPA我们自己签名也行

**Comment by carsonxu** [comment]
去年下半年，可下载了。
