### ISSUE TITLE
需求 - 剪切功能, 加星标功能

### ISSUE THREAD

**Issue by hollypeter** [TencentCloud/cosbrowser#187]
1. 客户端没有剪切？或者move to?
![image](https://user-images.githubusercontent.com/39903838/169703855-5b8b09ed-29d9-4485-ab77-767d80489d62.png)

2. 客户端能有“加星标”功能？快速访问指定bucket

**Comment by carsonxu** [comment]
![image](https://github.com/TencentCloud/cosbrowser/assets/24862812/92c8613e-e187-437e-bc81-52e4d9f146e8)
剪切暂不支持，桶/文件夹/文件已支持星标。
