### ISSUE TITLE
apple m1芯片早点支持不行吗？

### ISSUE THREAD

**Issue by kuke21** [TencentCloud/cosbrowser#190]
apple m1芯片早点支持不行吗？ 你们发布工具好歹也吧兼容做出来吧 都快2年了 动都不动一下，赖蛤蟆？

**Comment by carsonxu** [comment]
验证过M1没兼容问题

**Comment by carsonxu** [comment]
https://cloud.tencent.com/document/product/436/11366
已改为两个包：区分 macOS Intel 芯片版、macOS Apple 芯片版
