### ISSUE TITLE
希望在文件预览页面增加删除按钮，方便审查文件直接删除操作。

### ISSUE THREAD

**Issue by sisui9847** [TencentCloud/cosbrowser#191]
1、希望在文件预览页面增加删除按钮，方便审查文件直接删除操作。
![Uploading image.png…]()

2、也可以增强文件显示效果，在所有文件状态下，网格布局可以直接显示文件缩略图，就可以在不点开文件的情况下直接预览与操作。

**Comment by Wonder233** [comment]
目前网格布局已经可以展示文件缩略图了，需要您开启万象的功能。
在网格布局中右键菜单可以打开缩略图预览功能。
