### ISSUE TITLE
客户端报错：unable to get local issuer certificate，无法上传文件

### ISSUE THREAD

**Issue by xiaoch11** [TencentCloud/cosbrowser#194]
如题，今天上午10:50左右正常使用过程中突然出现报错，无法上传文件，且无法查看文件目录

**Comment by Wonder233** [comment]
这个可能是你本地DNS缓存的证书有问题，可以清理一下DNS缓存。

**Comment by wenfh2020** [comment]
我这也出现这个问题，某个文件夹有这个问题，其它文件夹是正常的；第二天又正常了。清理过 DNS 后重新登录客户端问题依然存在。
——我去，这个问题还是去年的，研发能不能重视一下。
