### ISSUE TITLE
上传完成的文件，依旧显示在上传列表中

### ISSUE THREAD

**Issue by cooper1x** [TencentCloud/cosbrowser#196]
![image](https://user-images.githubusercontent.com/9080789/173278633-3af524e5-f9e6-4eac-a4a0-e56133f7ce42.png)

**Comment by Wonder233** [comment]
您好，交互是这么设计的。上传列表包括了【上传中】【失败】【已完成】三种状态的上传文件。下载列表同理。
![image](https://user-images.githubusercontent.com/8199240/187874846-c30ed013-7776-4ff9-bf0e-abb934a31d2c.png)
