### ISSUE TITLE
[Bug] HTTP header editing not working on Windows client

### ISSUE THREAD

**Issue by Nemo-G** [TencentCloud/cosbrowser#198]
Found on Windows client, Version v 2.8.7

Behavior:
1. Select detail of object and open `Custom Header` panel, the UI and notification showed success but it didn't survive after refreshing.
2. If editing from dropdown, I can see failure notification. (You can also find a typo on the screenshot)
![image](https://user-images.githubusercontent.com/4470810/185209198-c13aa68b-7d47-4dd3-a007-988ff8980d11.png)
3. When trying to re-upload, there seems no option for `Content-Encoding` while I can see this option when editing.

There seems no such feature on Web/Chrome plugin. Also I didn't find how to edit via COSCMD tool.

Finally I managed to set it on the Mac client( v 2.8.7). It seems that it is the only way. Is there any way other than `COSBrowser` that can achieve this?

**Comment by Nemo-G** [comment]
The success notification will show but in fact it doesn't update.

**Comment by carsonxu** [comment]
fixed
