### ISSUE TITLE
收藏、统计功能建议

### ISSUE THREAD

**Issue by NwpuPc** [TencentCloud/cosbrowser#199]
希望能增加以下功能：
1.收藏功能，常用的路径的收藏
2.统计文件夹大小的功能

**Comment by carsonxu** [comment]
![image](https://github.com/TencentCloud/cosbrowser/assets/24862812/ba41eb70-cb38-4eb2-97c2-1ce5df74bdec)
![image](https://github.com/TencentCloud/cosbrowser/assets/24862812/b3eab383-8f0b-4e49-aa78-aa0d1ab9470c)
收藏、统计，已支持
