### ISSUE TITLE
cosbrowser 定时同步，建议新增比较同步功能。文件比较多时每次覆盖同步，太浪费时间。

### ISSUE THREAD

**Issue by binston** [TencentCloud/cosbrowser#201]
cosbrowser 工具箱中的定时同步 建议新增比较同步功能 （或者可以设置覆盖的规则）
文件比较多时每次覆盖同步，太浪费时间。

**Comment by carsonxu** [comment]
已经有的，工具箱里有个文件对比。

![image](https://user-images.githubusercontent.com/24862812/191234508-6ca910e7-5be5-4135-8ab9-0d4fd6f4770a.png)

![image](https://user-images.githubusercontent.com/24862812/191234433-5967fc0b-4c44-481b-b407-dee9e401add5.png)
