### ISSUE TITLE
cos太二了，和阿里的ossbrowser没法比。就冲这一点，建议大家用阿里云。

### ISSUE THREAD

**Issue by DachuanZhao** [TencentCloud/cosbrowser#210]
1 默认加个桶前缀，每次拷贝过来cosn链接的时候，都得费劲自己把前面的删了。

2 在链接框中选中内容的时候，鼠标超出软件边界，选中就会自动取消。

3 还没有 上一级 按钮，抄 windows资源管理器 不会抄么？？？

真踏马的太二了。。。

**Comment by Wonder233** [comment]
您好，您提的第一个问题不太明白您的需求是什么。
第二点确实是有问题，已提给开发进行处理。
第三点您可以在下图处点击面包屑导航进行路径回退，也可以通过左右按钮进行前进后退。
![image](https://user-images.githubusercontent.com/8199240/228186466-c29613fc-b9c1-4c7d-b7d8-d77ef7b2f35f.png)

**Comment by DachuanZhao** [comment]
> 您好，您提的第一个问题不太明白您的需求是什么。 第二点确实是有问题，已提给开发进行处理。 第三点您可以在下图处点击面包屑导航进行路径回退，也可以通过左右按钮进行前进后退。 ![image](https://user-images.githubusercontent.com/8199240/228186466-c29613fc-b9c1-4c7d-b7d8-d77ef7b2f35f.png)

第一个问题需求就是学学 oss，直接把链接copy过来，敲个enter就能直接进，而不是费劲的还得把前缀删了。

要是不同的bucket，这种操作更费劲。。。

第三个更是无力吐槽，只是培养用户习惯么？windows资源管理器不也有 面包屑 + 向上 ？
