### ISSUE TITLE
文件同步功能失效

### ISSUE THREAD

**Issue by betamaoIS** [TencentCloud/cosbrowser#211]
版本：v 2.11.0
平台：MacOS 13.2
问题描述：
文件同步功能失效，判断为无更新，未执行同步，如下
<img width="783" alt="Snipaste_2023-02-23_11-02-52" src="https://user-images.githubusercontent.com/24752088/220812767-4e675645-772a-46f2-997b-688a771c82bb.png">

**Comment by drtwww** [comment]
我还以为就我出问题，没想到大家都不能同步。
更新还不如不更新，火大，这个问题出现到现在为止已经第3天了，不知道贵司员工天天996在996些什么东西。

**Comment by carsonxu** [comment]
清除缓存是否可以继续同步？ @drtwww @betamaoIS

**Comment by ericjiajia** [comment]
@drtwww @betamaoIS 
今日的2.11.1版本已修复该问题，请更新后使用，造成的麻烦敬请谅解。

**Comment by betamaoIS** [comment]
@ericjiajia 测试没问题啦，感谢🙏
