### ISSUE TITLE
安装完成后打开COSBrowser白屏无显示

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [TencentCloud/cosbrowser#213]
如图
![image](https://github.com/TencentCloud/cosbrowser/assets/42903464/bf9a2ac3-5551-4edc-a262-d94fc48d902f)

**Comment by carsonxu** [comment]
系统、版本、内存配置都发一下

**Comment by Shiroiame-Kusu** [comment]
Device name	Kusunoki
Processor	Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz   3.00 GHz
Installed RAM	32.0 GB
Edition	Windows 11 Pro for Workstations
Version	22H2
Installed on	‎5/‎7/‎2023
OS build	25357.1
Experience	Windows Feature Experience Pack 1000.25350.1000.0

**Comment by carsonxu** [comment]
版本有点老，试试最新版本，先关单。
