### ISSUE TITLE
存储桶列表上鼠标右键查看其他桶（非当前选中的桶）的详情时，展示的信息依然是当前选中桶

### ISSUE THREAD

**Issue by whinc** [TencentCloud/cosbrowser#221]
问题如题，例如在点击选中桶 A 后，在桶 B 上鼠标右键查看桶详情，显示的信息依然是桶 A 的，不符合用户习惯和预期

![image](https://github.com/TencentCloud/cosbrowser/assets/5096493/87148ac5-8b44-4913-a878-647b81273487)

**Comment by carsonxu** [comment]
这里右键其实是在右键右侧的文件列表空白区域。
已优化。排除了左侧不可右键。
