### ISSUE TITLE
需求反馈：需要可以一次分享多个文件夹的功能

### ISSUE THREAD

**Issue by yinworth** [TencentCloud/cosbrowser#223]

**Comment by carsonxu** [comment]
选中多个文件夹后，是希望产生多个分享链接，还是一个分享链接？

**Comment by yinworth** [comment]
> 选中多个文件夹后，是希望产生多个分享链接，还是一个分享链接？
> 如果是一个分享链接，可以考虑在父目录操作分享。

想分享一个链接，如果分享父目录，其他不想分享的文件夹也会被看到

**Comment by carsonxu** [comment]
暂不支持。
