### ISSUE TITLE
apple m1 芯片需要确认兼容性。

### ISSUE THREAD

**Issue by carsonxu** [TencentCloud/cosbrowser#226]
多次验证过 Mac M1 环境，cosbrowser 最新版本的 dmg 是支持的。
用户反馈还有兼容问题。这里再开一个 issue 跟进处理。
关联帖子：https://www.v2ex.com/t/984960

**Comment by carsonxu** [comment]
https://cloud.tencent.com/document/product/436/11366
已改为两个包：区分 macOS Intel 芯片版、macOS Apple 芯片版

**Comment by buildyuan** [comment]
macOS Apple 芯片版 收到更新通知后，会自动更新到 Intel 芯片版
