### ISSUE TITLE
[bug]v2.11.12 arm64 历史会话无法保存密钥

### ISSUE THREAD

**Issue by buildyuan** [TencentCloud/cosbrowser#227]
复现步骤：
场景一：
1、打开cosbrowser，密钥登录（勾选会话）
2、退出cosbrowser
3、重新打开cosbrowser，打开的是登录页面，SecretKey栏空
场景二：
1、打开cosbrowser，点击历史会话
2、选择已保存的会话
3、点击使用，打开的是登录页面，SecretKey栏空
场景三：
1、密钥登录完成以后
2、点击右上角头像，
3、点击切换会话
4、点击任意已保存的会话后面的“切换”按钮
3、打开的是登录页面，SecretKey栏空，顶部浮层报错：未知错误{"code":"noAuthorization"}

**Comment by carsonxu** [comment]
v2.11.15 已修复，感谢反馈
