### ISSUE TITLE
图标都不见了

### ISSUE THREAD

**Issue by lizixian2016** [TencentCloud/cosbrowser#233]
打开软件之后里面的图标都不见了，
卸载重装也是没有图标；菜单图标，文件图标都没了

**Comment by carsonxu** [comment]
给个截图？

**Comment by lizixian2016** [comment]
> 给个截图？

![微信截图_20240125145718](https://github.com/TencentCloud/cosbrowser/assets/22340074/70fb25a9-8aad-4eea-90c3-81eaeda050c9)

**Comment by lizixian2016** [comment]
![image](https://github.com/TencentCloud/cosbrowser/assets/22340074/a6359db7-bff4-4f51-98b5-ab4ccf7c7a20)

**Comment by codingcn** [comment]
一样的问题

**Comment by lizixian2016** [comment]
你好，这个bug修改好了？怎关闭issues了？
我这边更新到最新版本还是存在这个问题的，windows11
