### ISSUE TITLE
重启后 Secret Key 不能记住

### ISSUE THREAD

**Issue by taurusxin** [TencentCloud/cosbrowser#234]
每次重启App后Secret Key都要重新填，并且历史会话中也没法记住。

**Comment by carsonxu** [comment]
已知问题，不分系统版本不兼容，近期会修复。

**Comment by taurusxin** [comment]
谢谢大佬，这工具真的棒！

**Comment by carsonxu** [comment]
确认是 macOS M1/M2 电脑，安装 Apple 芯片版本会有这个问题，已修复。@taurusxin
