### ISSUE TITLE
希望可以加入批量添加修改扩展名的功能

### ISSUE THREAD

**Issue by cooper1x** [TencentCloud/cosbrowser#82]
我用url转存后，发现都是没有后缀名的，而COS客户端不支持批量修改的操作，希望后续可以加入。

**Comment by carsonxu** [comment]
不考虑支持批量修改扩展名。
输入链接的弹窗加一个指定文件名的输入框，解决这个需求。

**Comment by cooper1x** [comment]
@carsonxu 这个输入连接的弹窗的入口在哪呢？我想试一下。

我这边url转存是在网页后台操作的，转存的是腾讯文档的图片url，发现文件名都是字符串没有后缀名。

之前为了把腾讯文档（有QQ空间防盗链）写好的文档，复制到微信开放社区发帖，我做下如下操作：
1. 腾讯文档复制内容
2. 粘贴到Yu Writer获取md格式
3. md粘贴到掘金编辑器
4. 编辑器转存图片后，复制右边预览内容到Yu Writer获取md格式（左边md加密了）
5. md的代码粘贴到vscode，做正则提取掘金图片链接操作
6. 新建文档，粘贴图片链接，上传到腾讯云COS迁移平台
7. 转换成功后，图片拉回本地，添加后缀名png
8. 重新上传，vscode中进行2次操作批量正则替换
9. 复制最终版的md代码到微信开放社区编辑器，提交

经过了这一系列的操作，目的是想把cos作为我的md图床，让图片链接随处可用不丢失。

之前用的各大平台在线文档，都只能导入不能完整导出，因此有了这个需求。
