### ISSUE TITLE
客户端可以重命名文件夹么

### ISSUE THREAD

**Issue by Caimengfan** [TencentCloud/cosbrowser#87]
刚开始用，发现不能再客户端上重命名文件夹，只能在网页上重命名，是否有这个功能或者增加该功能

**Comment by carsonxu** [comment]
这里重命名文件夹其实是队列面文件逐个复制删除了一遍，所以比较复杂，后面会支持。

**Comment by Caimengfan** [comment]
好的，期待下次更新



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "carsonxu"<notifications@github.com&gt;; 
发送时间: 2020年1月10日(星期五) 晚上6:29
收件人: "tencentyun/cosbrowser"<cosbrowser@noreply.github.com&gt;; 
抄送: "林夕凡"<907103260@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tencentyun/cosbrowser] 客户端可以重命名文件夹么 (#87)




这里重命名文件夹其实是队列面文件逐个复制删除了一遍，所以比较复杂，后面会支持。
